Regenerate SDAM JSON tests with yaml2json

diff --git a/source/server-discovery-and-monitoring/tests/Makefile b/source/server-discovery-and-monitoring/tests/Makefile
--- a/source/server-discovery-and-monitoring/tests/Makefile
+++ b/source/server-discovery-and-monitoring/tests/Makefile
@@ -1,8 +1,16 @@
 YAML_FILES=$(shell find . -iname '*.yml')
 JSON_FILES=$(patsubst %.yml,%.json,$(YAML_FILES))
 
-all: $(JSON_FILES)
+HAS_YAML2JSON:
+	@if ! command -v yaml2json > /dev/null; then               \
+	    echo 'Error: need "npm install -g yaml-to-json"' 1>&2; \
+	    exit 1;                                                \
+	fi
+
+.PHONY: HAS_YAML2JSON
+
+all: $(JSON_FILES) HAS_YAML2JSON
 
 %.json : %.yml
-	jwc yaml2json $< > $@
+	yaml2json $< > $@
 
