refactor(yml): change the tool we use for generating json from yml
SPEC-910

diff --git a/source/Makefile b/source/Makefile
--- a/source/Makefile
+++ b/source/Makefile
@@ -1,13 +1,13 @@
 YAML_FILES=$(shell find . -iname '*.yml')
 JSON_FILES=$(patsubst %.yml,%.json,$(YAML_FILES))
 
-all: $(JSON_FILES) HAS_YAML2JSON
+all: $(JSON_FILES) HAS_JSYAML
 
 %.json: %.yml
-	yaml2json $< > $@
+	js-yaml $< > $@
 
-HAS_YAML2JSON:
-	@if ! command -v yaml2json > /dev/null; then            \
-	    echo 'Error: need "npm install yaml-to-json"' 1>&2; \
-	    exit 1;                                             \
+HAS_JSYAML:
+	@if ! command -v js-yaml > /dev/null; then            \
+	    echo 'Error: need "npm install -g js-yaml"' 1>&2; \
+	    exit 1;                                           \
 	fi
