DRIVERS-709 wip

diff --git a/source/Makefile b/source/Makefile
--- a/source/Makefile
+++ b/source/Makefile
@@ -17,3 +17,9 @@ HAS_JSYAML:
 	    echo 'Error: need "npm install -g js-yaml"' 1>&2; \
 	    exit 1;                                           \
 	fi
+
+HAS_AJV:
+	@if ! command -v ajv > /dev/null; then            \
+	    echo 'Error: need "npm install -g ajv"' 1>&2; \
+	    exit 1;                                           \
+	fi
